spring:
  datasource:
    url: jdbc:mysql://39.106.169.107:3306/study
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Ali_005448
  application:
    name: ImgInClass
mybatis:
  mapper-locations: classpath:mapping/*.xml

server:
  port: 8081