package MybatisTest.dao;

import MybatisTest.dataObject.PicDO;
import org.springframework.stereotype.Component;

@Component
public interface PicDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    int insert(PicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    int insertSelective(PicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    PicDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    int updateByPrimaryKeySelective(PicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    int updateByPrimaryKey(PicDO record);
}