package MybatisTest.dataObject;

public class PicDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.name
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.mei_tui
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer meiTui;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.ju_ru
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer juRu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.zhi_fu
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer zhiFu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.bai_he
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer baiHe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.mei_mou
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer meiMou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.bai
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer bai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.hei_si
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer heiSi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.papa
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer papa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.se_qi
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer seQi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.LOL
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer lol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.hua_gong
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer huaGong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.large_ru
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    private Integer largeRu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.name
     *
     * @return the value of pic.name
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.name
     *
     * @param name the value for pic.name
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.mei_tui
     *
     * @return the value of pic.mei_tui
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getMeiTui() {
        return meiTui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.mei_tui
     *
     * @param meiTui the value for pic.mei_tui
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setMeiTui(Integer meiTui) {
        this.meiTui = meiTui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.ju_ru
     *
     * @return the value of pic.ju_ru
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getJuRu() {
        return juRu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.ju_ru
     *
     * @param juRu the value for pic.ju_ru
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setJuRu(Integer juRu) {
        this.juRu = juRu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.zhi_fu
     *
     * @return the value of pic.zhi_fu
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getZhiFu() {
        return zhiFu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.zhi_fu
     *
     * @param zhiFu the value for pic.zhi_fu
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setZhiFu(Integer zhiFu) {
        this.zhiFu = zhiFu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.bai_he
     *
     * @return the value of pic.bai_he
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getBaiHe() {
        return baiHe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.bai_he
     *
     * @param baiHe the value for pic.bai_he
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setBaiHe(Integer baiHe) {
        this.baiHe = baiHe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.mei_mou
     *
     * @return the value of pic.mei_mou
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getMeiMou() {
        return meiMou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.mei_mou
     *
     * @param meiMou the value for pic.mei_mou
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setMeiMou(Integer meiMou) {
        this.meiMou = meiMou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.bai
     *
     * @return the value of pic.bai
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getBai() {
        return bai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.bai
     *
     * @param bai the value for pic.bai
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setBai(Integer bai) {
        this.bai = bai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.hei_si
     *
     * @return the value of pic.hei_si
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getHeiSi() {
        return heiSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.hei_si
     *
     * @param heiSi the value for pic.hei_si
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setHeiSi(Integer heiSi) {
        this.heiSi = heiSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.papa
     *
     * @return the value of pic.papa
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getPapa() {
        return papa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.papa
     *
     * @param papa the value for pic.papa
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setPapa(Integer papa) {
        this.papa = papa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.se_qi
     *
     * @return the value of pic.se_qi
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getSeQi() {
        return seQi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.se_qi
     *
     * @param seQi the value for pic.se_qi
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setSeQi(Integer seQi) {
        this.seQi = seQi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.LOL
     *
     * @return the value of pic.LOL
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getLol() {
        return lol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.LOL
     *
     * @param lol the value for pic.LOL
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setLol(Integer lol) {
        this.lol = lol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.hua_gong
     *
     * @return the value of pic.hua_gong
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getHuaGong() {
        return huaGong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.hua_gong
     *
     * @param huaGong the value for pic.hua_gong
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setHuaGong(Integer huaGong) {
        this.huaGong = huaGong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.large_ru
     *
     * @return the value of pic.large_ru
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public Integer getLargeRu() {
        return largeRu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.large_ru
     *
     * @param largeRu the value for pic.large_ru
     *
     * @mbg.generated Thu Mar 26 20:00:24 CST 2020
     */
    public void setLargeRu(Integer largeRu) {
        this.largeRu = largeRu;
    }
}